package coordinator

import (
	"crypto/rand"
	"encoding/hex"
	"strings"
	"sync"
	"time"
)

// =============================================================================
// Self-Suppression — Prevent Observer from alerting on its own verify requests
// =============================================================================
//
// PROBLEM:
//   When Observer makes a verify request to confirm a catch-all, nginx logs it.
//   Observer then reads that log line and would classify it as suspicious.
//   We need to suppress our own housekeeping without creating an attacker bypass.
//
// SOLUTION (design consensus, 2026-03-31):
//   Generate a cryptographically random token per verify request. Embed it in
//   the User-Agent header. Store it in a time-limited pending set. When a log
//   line arrives, check if it contains any pending token. Only suppress on match.
//
//   An attacker cannot predict the token. They'd have to guess a random 16-byte
//   hex string within a 10-second window. Cryptographically infeasible.
//
//   the design review's mandate: "No static strings that an attacker can copy."
//   code review's alternative (loopback IP) was considered but Docker port publishing
//   may not preserve 127.0.0.1 as the source IP in nginx logs.

const (
	tokenLength      = 16 // bytes → 32 hex chars
	tokenTTL         = 10 * time.Second
	tokenPrefix      = "OV-" // prefix in User-Agent: "OV-a8f72b4c1d3e..."
	maxPendingTokens = 50
)

// SelfSuppressor manages ephemeral tokens for verify request self-identification.
type SelfSuppressor struct {
	mu      sync.Mutex
	pending map[string]time.Time // token → expiry time
}

// NewSelfSuppressor creates a new self-suppression registry.
func NewSelfSuppressor() *SelfSuppressor {
	return &SelfSuppressor{
		pending: make(map[string]time.Time),
	}
}

// GenerateToken creates a new random token, registers it in the pending set,
// and returns the full User-Agent string to use in the verify request.
// The token auto-expires after tokenTTL.
func (s *SelfSuppressor) GenerateToken() (userAgent string, token string) {
	b := make([]byte, tokenLength)
	if _, err := rand.Read(b); err != nil {
		// Fallback — still random enough to avoid collision
		b = []byte(time.Now().String())
	}
	token = tokenPrefix + hex.EncodeToString(b)

	s.mu.Lock()
	defer s.mu.Unlock()

	// Clean expired tokens
	now := time.Now()
	for t, expiry := range s.pending {
		if now.After(expiry) {
			delete(s.pending, t)
		}
	}

	// Cap total pending tokens (safety valve)
	if len(s.pending) >= maxPendingTokens {
		// Evict oldest
		var oldestToken string
		var oldestExpiry time.Time
		for t, exp := range s.pending {
			if oldestToken == "" || exp.Before(oldestExpiry) {
				oldestToken = t
				oldestExpiry = exp
			}
		}
		delete(s.pending, oldestToken)
	}

	s.pending[token] = now.Add(tokenTTL)
	return "Observer-Verify/" + token, token
}

// IsSelfVerify checks if a raw log line contains any active self-suppression token.
// Returns true if this log line was generated by Observer's own verify request.
func (s *SelfSuppressor) IsSelfVerify(rawLine string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()

	now := time.Now()
	for token, expiry := range s.pending {
		if now.After(expiry) {
			delete(s.pending, token)
			continue
		}
		if strings.Contains(rawLine, token) {
			// Found it — consume the token (one-shot)
			delete(s.pending, token)
			return true
		}
	}
	return false
}
