package rec

import (
	"crypto/sha256"
	"fmt"
	"time"
)

// =============================================================================
// Evidence Status — The "Why Did It Fail" State Machine
// =============================================================================
//
// Every evidence lookup returns an explicit status, not just nil/non-nil.
// This is critical for debugging and journal logging. When you see
// EvidenceStatus=not_available_no_match in journalctl at 2am,
// you know exactly why there's no evidence — no guessing.

type EvidenceStatus string

const (
	// Evidence was found and correlation confidence is high.
	// Single matching response within the time window.
	EvidenceAvailableHighConfidence EvidenceStatus = "available_high_confidence"

	// Evidence was found but multiple responses matched.
	// Transport metadata is included, body preview is NOT (dual-gate).
	EvidenceAvailableLowConfidence EvidenceStatus = "available_low_confidence"

	// REC is disabled (missing CAP_NET_RAW, not opted in, etc.)
	EvidenceNotAvailableCollectorDisabled EvidenceStatus = "not_available_collector_disabled"

	// REC is running but no matching response was found in the buffer.
	//
	// PHASE 1 HONESTY: This is the catch-all "not found" status. Phase 1
	// cannot reliably distinguish WHY there's no match — it could be an
	// edge-generated response (proxy blind spot), evicted from the buffer,
	// or encrypted backend traffic. The statuses below exist in the enum
	// for API stability so future phases can promote to specific reasons
	// without breaking consumers. Phase 1 almost always returns this one.
	EvidenceNotAvailableNoMatch EvidenceStatus = "not_available_no_match"

	// FUTURE (Phase 2+): A match existed but was evicted before lookup.
	// Requires buffer-level eviction tracking correlated to pending lookups.
	// Not emitted in Phase 1 — here for API stability.
	EvidenceNotAvailableEvicted EvidenceStatus = "not_available_evicted"

	// FUTURE (Phase 2+): Response was generated by the edge proxy itself
	// (nginx/caddy/traefik) and never traversed the plaintext backend
	// network where REC captures.
	// Examples: 403 block pages, 404 static file misses, redirects.
	// THE PROXY BLIND SPOT — Phase 1 cannot see these responses.
	// Detection hint: nginx logs upstream_response_time as "-" when it
	// handles the response directly. Not parsed in Phase 1.
	EvidenceNotAvailableEdgeGenerated EvidenceStatus = "not_available_edge_generated"

	// FUTURE (Phase 2+): The response path is encrypted (mTLS between
	// proxy and backend). Phase 2 (eBPF) would address this.
	EvidenceNotAvailableEncryptedPath EvidenceStatus = "not_available_encrypted_path"
)

// =============================================================================
// Confidence Levels — Used for the Dual-Gate Security Rule
// =============================================================================

type Confidence string

const (
	ConfidenceHigh Confidence = "high"
	ConfidenceLow  Confidence = "low"
	ConfidenceNone Confidence = "none"
)

// =============================================================================
// Detected Format — What the redaction classifier thinks the body is
// =============================================================================

type DetectedFormat string

const (
	FormatDotenv  DetectedFormat = "dotenv"
	FormatJSON    DetectedFormat = "json"
	FormatPasswd  DetectedFormat = "passwd"
	FormatHTML    DetectedFormat = "html"
	FormatXML     DetectedFormat = "xml"
	FormatBinary  DetectedFormat = "binary"
	FormatUnknown DetectedFormat = "unknown"
)

// =============================================================================
// Transport Evidence — Layer 1 (always present when status is available_*)
// =============================================================================
//
// Mechanical "what the server returned" layer.
// Safe to include in every alert — no secrets, just metadata.

type TransportEvidence struct {
	StatusCode      int           `json:"status_code"`
	ContentType     string        `json:"content_type"`
	ContentLength   int64         `json:"content_length"`        // from headers (may differ from actual body size)
	CapturedAt      time.Time     `json:"captured_at"`
	ResponseLatency time.Duration `json:"response_latency,omitempty"`

	// SHA-256 hash of the captured body PREVIEW, not the full response body.
	// Phase 1 captures only what fits in a single TCP segment after headers.
	// Do NOT treat this as a forensic hash of the complete response.
	// (code review's catch: don't lie in the type.)
	BodyPreviewHash string `json:"body_preview_hash"`

	// How this evidence was captured. Tells consumers how much to trust it.
	// Phase 1 is always "single_segment_preview" — headers and partial body
	// from one TCP segment. Future phases may add "full_stream" etc.
	// (code review's catch: mark capture as partial so users don't over-read.)
	CaptureMode string `json:"capture_mode"`
}

// =============================================================================
// Disclosure Analysis — Layer 2 (format + summary)
// =============================================================================
//
// "What that probably means" layer. Contains format detection and summary.
//
// NOTE: The body preview itself lives on Evidence.SafeBodyPreview, NOT here.
// The dual-gate rule is enforced at construction time in liveCollector.Lookup().
// This avoids the unexported-field JSON serialization trap ('s catch).
//
// NOTE: classifyAndRedact() operates on the TRUNCATED body preview (max 2KB),
// not the full response body. Format detection and redaction confidence are
// therefore based on partial content. Acceptable for Phase 1 MVP.

type DisclosureAnalysis struct {
	// What format the classifier detected (based on truncated preview)
	Format DetectedFormat `json:"format"`

	// Classifier confidence. Based on partial content — see note above.
	RedactionConfidence Confidence `json:"redaction_confidence"`

	// Human-readable assessment.
	// Examples: "DOTENV STRUCTURE DETECTED", "UNKNOWN FORMAT — METADATA ONLY"
	DisclosureSummary string `json:"disclosure_summary"`

	// Package-internal: the raw redacted preview before dual-gate evaluation.
	// Unexported deliberately — it does NOT serialize to JSON.
	// The dual-gate logic in liveCollector.Lookup() reads this field and
	// copies it to Evidence.SafeBodyPreview (exported) only if both gates pass.
	// This avoids the JSON serialization trap while keeping the redaction
	// result available for the gate check within the rec package.
	redactedPreview string
}

// =============================================================================
// Evidence — The Complete REC Result
// =============================================================================

type Evidence struct {
	// The explicit status — ALWAYS check this first.
	Status EvidenceStatus `json:"status"`

	// How confident REC is that this response belongs to the triggering request.
	CorrelationConfidence Confidence `json:"correlation_confidence"`

	// Layer 1 — transport metadata (present when status is available_*)
	Transport *TransportEvidence `json:"transport,omitempty"`

	// Layer 2 — disclosure analysis (present when status is available_*)
	Disclosure *DisclosureAnalysis `json:"disclosure,omitempty"`

	// The structurally-redacted body preview.
	//
	// DUAL-GATE RULE: Only populated when BOTH gates pass at construction:
	//   1. CorrelationConfidence == High (correct response matched)
	//   2. RedactionConfidence  == High (secrets properly redacted)
	// If either gate fails, this is empty string. Period.
	//
	// Evaluated once in liveCollector.Lookup(), not lazily via getter.
	// Exported so it serializes correctly to JSON for dashboards/APIs/storage.
	// (Fix for 's JSON serialization catch on unexported fields.)
	SafeBodyPreview string `json:"safe_body_preview,omitempty"`

	// Number of candidate responses found during correlation.
	// 1 = high confidence, 2+ = low confidence, 0 = no match.
	CandidateCount int `json:"candidate_count"`
}

// HasEvidence returns true if any evidence (even metadata-only) is available.
func (e *Evidence) HasEvidence() bool {
	if e == nil {
		return false
	}
	return e.Status == EvidenceAvailableHighConfidence ||
		e.Status == EvidenceAvailableLowConfidence
}

// ForJournal returns a compact string for journal/log output.
// Always includes Status and Correlation — even when no evidence found.
//
// Examples:
//   EvidenceStatus=available_high_confidence Correlation=high StatusCode=200 ContentLength=45032 BodyHash=sha256:a3f2b8c9... Format=dotenv
//   EvidenceStatus=not_available_no_match Correlation=none
//   EvidenceStatus=not_available_collector_disabled Correlation=none
func (e *Evidence) ForJournal() string {
	if e == nil {
		return "EvidenceStatus=not_available_collector_disabled Correlation=none"
	}
	s := fmt.Sprintf("EvidenceStatus=%s Correlation=%s", e.Status, e.CorrelationConfidence)
	if e.HasEvidence() && e.Transport != nil {
		s += fmt.Sprintf(" StatusCode=%d ContentLength=%d BodyPreviewHash=sha256:%.16s CaptureMode=%s",
			e.Transport.StatusCode,
			e.Transport.ContentLength,
			e.Transport.BodyPreviewHash,
			e.Transport.CaptureMode,
		)
		if e.Disclosure != nil {
			s += fmt.Sprintf(" Format=%s Disclosure=%q", e.Disclosure.Format, e.Disclosure.DisclosureSummary)
		}
		if e.SafeBodyPreview != "" {
			s += " HasPreview=true"
		}
	}
	return s
}

// =============================================================================
// Helpers
// =============================================================================

// HashBody computes the SHA-256 hex digest of a response body.
func HashBody(body []byte) string {
	h := sha256.Sum256(body)
	return fmt.Sprintf("%x", h[:])
}